### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @snaildos.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@snaildos please review 🙏🏻

**Comment by snaildos** [comment]
> @snaildos please review 🙏🏻

Hi! I appreciate your PR but tbh I don't see the point of a Github Action, it's fairly annoying and I just prefer everything manually goes through the workflow when publishing a release, I will look into this soon.

**Comment by vedantmgoyal2009** [comment]
Hi, you don't need manually run the workflow everytime use publish a release. GitHub Actions will automatically trigger the workflow and the manifests of SnailFM will be updated at WinGet without any human action.

**Comment by snaildos** [comment]
> Hi, you don't need manually run the workflow every time publish a release. GitHub Actions will automatically trigger the workflow and the manifests of SnailFM will be updated at WinGet without any human action.

Yeah, I know, but the concept of automating the workflow on our application suite isn't really intriguing to me. I might re-open after reconsidering, but at this current state I do not see a point.

**Comment by snaildos** [comment]
I'm going to integrate this now.

**Pull request merged**
